### PR TITLE
Add libopenblas.so without suffix

### PR DESCRIPTION
**Pull request by massich**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by massich** [comment]
@conda-forge-admin please rerender

**Comment by isuruf** [comment]
This is not correct. The `.so` should go in the `openblas` output and not `libopenblas` output

**Comment by massich** [comment]
I'm trying to run `smithy` but I get the following error:
```sh
~/repos/openblas-feedstock/recipe add_so 49s
(openmeeg-feedstock-test) ❯ conda update conda-smithy -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


~/repos/openblas-feedstock/recipe add_so
(openmeeg-feedstock-test) ❯ conda smithy recipe-lint .              
Traceback (most recent call last):
  File "/home/sik/miniconda3/envs/openmeeg-feedstock-test/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/sik/miniconda3/envs/openmeeg-feedstock-test/lib/python3.7/site-packages/conda_smithy/cli.py", line 477, in main
    args.subcommand_func(args)
  File "/home/sik/miniconda3/envs/openmeeg-feedstock-test/lib/python3.7/site-packages/conda_smithy/cli.py", line 372, in __call__
    return_hints=True,
  File "/home/sik/miniconda3/envs/openmeeg-feedstock-test/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 574, in main
    results, hints = lintify(meta, recipe_dir, conda_forge)
  File "/home/sik/miniconda3/envs/openmeeg-feedstock-test/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 392, in lintify
    for requirement in requirements:
TypeError: 'NoneType' object is not iterable
```

**Comment by isuruf** [comment]
@massich, https://github.com/conda-forge/conda-smithy/pull/1175

**Comment by massich** [comment]
@isuruf do you know how to patch it without the help of smithy?

**Comment by isuruf** [comment]
Edit `/home/sik/miniconda3/envs/openmeeg-feedstock-test/lib/python3.7/site-packages/conda_smithy/lint_recipe.py` ?

**Comment by massich** [comment]
any idea why `conda-forge-linter` is complaining? it passes with `conda-smithy (master)` passes

```sh
~/repos/openblas-feedstock/recipe add_so
(openmeeg-feedstock-test) ❯ conda smithy recipe-lint .        
. is in fine form
```

**Pull request merged**
