### PR TITLE
Use openmp on osx

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
We are using `llvm-openmp` with both `gfortran 7.3` and `clang 9.0` and `llvm-openmp` is `fork` safe.

**Comment by beckermr** [comment]
We should link that issue from the main issue tracker where this was discussed.

**Comment by beckermr** [comment]
found it: https://github.com/conda-forge/conda-forge.github.io/issues/831

**Comment by isuruf** [comment]
Merging as there was no objection.

**Pull request merged**
