### PR TITLE
OSX: Drop build-prefix rpath

### PR DESCRIPTION
**Pull request by jschueller**
The rpaths contain a BUILD_PREFIX entry, delete it to not confuse tools
such as delocate

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
some linux jobs fail due to connection issues,

the real problem is some test crashes for the osx "ilp64" variant:
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
2020-11-18T10:04:32.3203970Z 
2020-11-18T10:04:32.3204210Z Backtrace for this error:
2020-11-18T10:04:32.3244800Z #0  0x1066779cc
2020-11-18T10:04:32.3246980Z #1  0x106676dc5
2020-11-18T10:04:32.3251930Z #2  0x7fff6b0cb5fc
2020-11-18T10:04:32.3257810Z /bin/sh: line 1: 35444 Segmentation fault: 11  OMP_NUM_THREADS=2 ./xscblat2 < sin2
```

**Comment by isuruf** [comment]
This should probably be a change in `conda-build` at https://github.com/conda/conda-build/blob/3912c85c787741c11d713038f5a62fc52708032b/conda_build/post.py#L399

**Comment by jschueller** [comment]
So now we're removing the host prefix instead of the build prefix, at first thought I expected the build_prefix to be removed.
```
-            macho.delete_rpath(path, rpath, build_prefix=prefix, verbose=True)
+            macho.delete_rpath(path, join(host_prefix, rpath), build_prefix=prefix, verbose=True)
```

**Comment by isuruf** [comment]
Yes, conda-build never removed the paths in `build_prefix`. Absolute paths in `host_prefix` are removed because relative paths are added.

**Comment by jschueller** [comment]
ok, so I could remove build_prefix rpath there, thanks!

**Pull request closed without merging**
