### PR TITLE
Add .so symlinks

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Reverting the removal of symlinks in #62.

cc @isuruf

### CODE REVIEW

**Comment by jschueller** [comment]
+1, I was also needing this

**Comment by isuruf** [comment]
@jschueller, can you add your use-case to https://github.com/conda-forge/openblas-feedstock/issues/67 as well?

**Comment by isuruf** [comment]
These should go in https://github.com/conda-forge/blas-feedstock/blob/master/recipe/build_pkg.sh#L2 if they are to be added.

**Comment by SylvainCorlay** [comment]
> These should go in https://github.com/conda-forge/blas-feedstock/blob/master/recipe/build_pkg.sh#L2 if they are to be added.

@isuruf I am not sure about this. How can I know if all BLAS implementations will produce a `libblas.so.3` file and not some other suffix?

**Comment by isuruf** [comment]
They will. That's how this package is designed. Downstream packages will link to the netlib library which has soname 3 and we symlink that library to the optimized implementation in the other libblas variant.

**Comment by SylvainCorlay** [comment]
Thanks! Opening the blas-feedstock PR.

**Pull request closed without merging**
