### PR TITLE
WIP: Add windows support

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by jakirkham** [comment]
This is very interesting. However I️ think we need to come to a consensus on how new compilers will be used in conda-forge first. The compiler meeting should do that.

**Comment by xoviat** [comment]
So the main problem is how can I install a build dependency from another channel? We cannot use the conda forge cmake because building requires the development version. @jakirkham Any ideas?

**Comment by xoviat** [comment]
Also, this is not doing what you think it's doing. I'm testing to see whether the build will finish within the two-hour time limit.

**Comment by xoviat** [comment]
Also BTW, I think you will find the release notes for the next numpy version to be very interesting. I can only claim partial responsibility though.

**Pull request closed without merging**
