### PR TITLE
followup on scipy breaking

### PR DESCRIPTION
**Pull request by ngam**
https://github.com/conda-forge/openblas-feedstock/pull/146

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
Is the plan that we merge this and then see if scipy starts working again?

**Comment by rgommers** [comment]
What is the best way to download and install a package built in this PR?

**Comment by h-vetinari** [comment]
> What is the best way to download and install a package built in this PR?

Needs the following in `conda-forge.yml` plus a rerender:
```
# TODO: remove after debug
azure:
  store_build_artifacts: true
```

**Comment by h-vetinari** [comment]
> Already done.

Sorry I didn't check this (was on a phone...), seems you're well on top of things. ;)

> Once downloaded you can either:
>   1. upload to a personal channel and then pull down like usual with `-c yourchannel`

Note that you can use
```
conda install -c /path/to/where/you/unpacked/the/artefact openblas
```
if you download it directly.

**Comment by h-vetinari** [comment]
> Conclusion: as rgommers said, the errors are due to fortran updates (or more precisely, the automated updates in this PR).

Do we have any idea/intuition why a compiler upgrade would break this (well, aside from compiler regressions)...?

**Pull request closed without merging**
