### PR TITLE
Test pin gcc

### PR DESCRIPTION
**Pull request by ocefpaf**
This might help solve https://github.com/conda-forge/matplotlib-feedstock/issues/32, and https://github.com/conda-forge/numpy-feedstock/issues/15, but an ideal solution would be to have numpy+blas added to the build matrix somehow.

### CODE REVIEW

**Comment by jakirkham** [comment]
Sorry, @ocefpaf, this is not the solution. The solution is to make this only depend on `libgfortran`. Please see PR ( https://github.com/conda-forge/staged-recipes/pull/855 ).

**Comment by ocefpaf** [comment]
> Sorry, @ocefpaf, this is not the solution. The solution is to make this only depend on libgfortran. Please see PR ( conda-forge/staged-recipes#855 ).

I re-built everything in our docker image and this **does** fix the issue and ensure the stack is consistent. So this is a solution and we closer to the default channel with this one. Please re-consider that. There are more than one way to do things here. I am just trying to do what has a smaller burden on the maintainers and that will ensure stability in the long run.

Ping @msarahan and @pelson.

**Comment by jakirkham** [comment]
Have you looked at the other PR? The point is to make this depend only on `libgfortran`, which would also avoid having `libstdc++` and other unneeded stuff pulled in. Why does that not seem ok?

**Comment by ocefpaf** [comment]
> Have you looked at the other PR? 

If by other PR you mean https://github.com/conda-forge/staged-recipes/pull/855, then yes. That is why I wrote the text above.

**Comment by jakirkham** [comment]
I remain not in favor of the pinning of `libgcc`. This is something that is know to cause problems. If this gets pinned and the user installs this on a system with a newer version of `libgcc`, this will be totally broken. Sorry, I cannot conscientiously support this plan.

**Comment by ocefpaf** [comment]
> This is something that is know to cause problems. If this gets pinned and the user installs this on a system with a newer version of `libgcc`.

My system has a newer `gcc` and I do use conda packages compiled with the older `gcc`+`libgcc`. I don't see any problem there. I do know that `gcc` 5 ( @msarahan correct me if I am wrong) will bring trouble, but I cannot see how splitting will help.

Please don't reconsider as everything that uses numpy is broken right now. My actual was to request the deletion of the numpy package.

**Comment by jakirkham** [comment]
> My actual was to request the deletion of the numpy package.

Sorry, also not a fan of this. Let's focus on how we can split out `libgfortran`.

**Comment by ocefpaf** [comment]
> Sorry, also not a fan of this. Let's focus on how we can split out `libgfortran`.

I know, that is why I proposed this. However, at some point you will have to stop think about you and start thinking about the community.

# EVERYTHING THAT DEPENDS ON NUMPY IS BROKEN

Please try to get that.

**Comment by jakirkham** [comment]
Alright, let's take a deep breath.

There is a reason why I did try to propose a `libgfortran` package. While I think we may not understand the full cause of problems, that should at least eliminate `libstdc++` as a variable.

**Comment by ocefpaf** [comment]
>  While I think we may not understand the full cause of problems,

We -> you

**Comment by pelson** [comment]
@ocefpaf - are you able to help me understand *how* this fixes things? I don't expect this to fix the matplotlib issue simply because libstdc++ was being linked to by the matplotlib contour.so but not being installed because a different numpy was being installed. Is that not the case?

**Comment by ocefpaf** [comment]
> @ocefpaf - are you able to help me understand how this fixes things? 

The older `gcc`/`libgcc` is present is most Linux-es and this is the second best thing. The first one would be to remove the numpy with openblas altogether.

@pelson and @msarahan I am very upset with @jakirkham here as I see a double standard. When something is broken on is opinion he resorts to quick and solutions and self-merges that end up breaking stuff for others. When confronted with that he is adamant to change or even discuss.

Most of my community e-mails me when their env is broken and lately my fix has is: drop `conda-forge`. That **IS** terrible!! I am working on this `numpy` issue for a month!!! All I want is some sort of common sense here.

I am sure that if I was the one who added numpy with openblas and @jakirkham people were complaining he would have already revert everything. I am very upset with this.

**Comment by pelson** [comment]
There are no words to add to this IMO. I believe you have made your views clear and all I can hope is that we can all behave in a way that is consistent with the community's expectations. It is certainly a multi-way street and there is give, take and compromise needed for conda-forge to be a successful collaboration.

Ironically today is the EU :euro: Brexit vote it is a very similar debate: as a collaborative effort we have more influence at the cost of control, but as individuals we have more control with diminished influence.

Perhaps we need to prioritise a governance document which describes our community's expectations so that we can cite the document if we feel it is breached in someway. It would give all of us context of the things that are/aren't OK and it would help to communicate concerns more easily if things do come up.

**Comment by ocefpaf** [comment]
@pelson I sent this PR to start a discussion that was being killed simply b/c some people said: "it works for me."

I am happy to close this and keep discussing for a better solution.

I am just tired of being shot down when reporting important issues while I see self-merges that are hurting the community.

> Perhaps we need to prioritise a governance document which describes our community's expectations

+ :100:

**Comment by jakirkham** [comment]
To be honest, I find myself getting pings of all sorts of stuff broken here at conda-forge (very rarely does any of it affect me). I do the very best I can to try to improve the situation in any way I can as I have time. I have tried very hard to move slowly to be more community friendly as this was raised (though the removal at staged-recipes was clearly an error and I have since not been so hasty with such an issue). Unfortunately I don't have unlimited hours to spend here on all of the issues raised.

Though lately the overwhelming nature of this work is not the most stressful part. It's the fact that there is always someone extremely irate with me. I understand it is stressful when things don't work and I will do my best to help. Please don't take it out on me when that happens.

**Comment by ocefpaf** [comment]
> To be honest, I find myself getting pings of all sorts of stuff broken here at conda-forge (very rarely does any of it affect me).

Although most of my complains about you are when you hotfix and self-merges stuff!!!

I am not taking out on you. Sorry if you feel that way. I am calling on bad practices and asking for what I have being asking since the beginning. Patience!

You are always aggressive when I report bad practices and/or issue on software that you added, like numpy with openblas, sorry you feel that way. You need to stop feeling personally attacked and start thinking about what that did to the community. Numpy has been broken for a month! You could not wait hours in a similar situation not long ago. See the difference?

Also, I am trying to work with you on that while you only rejected the problem altogether! Derailed all my issue to another topics and/or blamed others.

@jakirkham I am not interested in you or point finger. I am interested in getting numpy fixed. For that I need that you, at least, acknowledge that there is a problem. (Which I think you finally did with this PR, but really do you remember the first time I brought this problem up to you? Think abou that.)

**Comment by jakirkham** [comment]
To be clear raising an issue or noting problems is not what is making me feel like I'm treated badly. It is totally reasonable to make apparent problems that you are having and this has no effect on me other than trying to help you fix them as I can.

Instead, it is the "yelling". While that is hard to quantify on GitHub, some examples include large bold font, excessive number of exclamation marks, lots of "you" language, etc.. It is unclear that any of this is needed to communicate the intended points. It is also something that I have not experienced elsewhere on GitHub (even in extremely tense discussions). Can we please try to avoid this style of communication?

**Pull request closed without merging**
