### PR TITLE
Carry patch for xianyi/OpenBLAS/pull/2729

### LINKED ISSUE #101: Segmantation fault with latest libopenblas 0.3.10
Issue:

We got a coredump with the latest version 0.3.10 (build 2): https://travis-ci.com/github/lldelisle/pyGenomeTracks/jobs/362129644#L974

`libopenblas-0.3.9` seems to work for us. Both versions (also 0.3.10-openmp_h709eae2_2) seems to cause the segfault.

```
$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> t = np.array([[1, 0.5], [-1, 0.5]])
>>> matrix_a = np.dot([(1,2)], t)
>>> matrix_a = np.dot([(1,2) for i in range(100)], t)
>>> matrix_a = np.dot([(1,2) for i in range(1000)], t)
>>> matrix_a = np.dot([(1,2) for i in range(10000)], t)
>>> matrix_a = np.dot([(1,2) for i in range(100000)], t)
>>> matrix_a = np.dot([(1,2) for i in range(1000000)], t)
Speicherzugriffsfehler (Speicherabzug geschrieben)

$ conda install libopenblas=0.3.9
Collecting package metadata (repodata.json): done
Solving environment: \ WARNING conda.resolve:_get_sat_solver_cls(57): Could not run SAT solver through interface 'pycryptosat'.
done

## Package Plan ##

  environment location: /home/bag/miniconda3/envs/pgt

  added / updated specs:
    - libopenblas=0.3.9


The following NEW packages will be INSTALLED:

  llvm-openmp        conda-forge/linux-64::llvm-openmp-10.0.0-hc9558a2_0

The following packages will be DOWNGRADED:

  _openmp_mutex                                   4.5-0_gnu --> 4.5-1_llvm
  libblas                                 3.8.0-17_openblas --> 3.8.0-16_openblas
  libcblas                                3.8.0-17_openblas --> 3.8.0-16_openblas
  liblapack                               3.8.0-17_openblas --> 3.8.0-16_openblas
  libopenblas                    0.3.10-pthreads_hb3c22a3_2 --> 0.3.9-h5ec1e0e_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(pgt) bag@bag:~/projects/code/pyGenomeTracks$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> t = np.array([[1, 0.5], [-1, 0.5]])
>>> matrix_a = np.dot([(1,2)], t)
>>> matrix_a = np.dot([(1,2) for i in range(100)], t)
>>> matrix_a = np.dot([(1,2) for i in range(1000)], t)
>>> matrix_a = np.dot([(1,2) for i in range(10000)], t)
>>> matrix_a = np.dot([(1,2) for i in range(100000)], t)
>>> matrix_a = np.dot([(1,2) for i in range(1000000)], t)
>>> 




```

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /home/bag/miniconda3/envs/pgt:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
argcomplete               1.12.0             pyh9f0ad1d_0    conda-forge
argh                      0.26.2                py37_1001    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
attrs                     19.3.0                     py_0    conda-forge
bedtools                  2.29.2               hc088bd4_0    bioconda
biopython                 1.76             py37h516909a_0    conda-forge
blosc                     1.19.0               he1b5a44_0    conda-forge
bokeh                     2.1.1            py37hc8dfbb8_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
cooler                    0.8.9              pyh864c0ab_0    bioconda
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.21.0                     py_0    conda-forge
dask-core                 2.21.0                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
dill                      0.3.2              pyh9f0ad1d_0    conda-forge
distributed               2.21.0           py37hc8dfbb8_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fsspec                    0.7.4                      py_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gffutils                  0.10.1                     py_0    bioconda
ghostscript               9.22              hf484d3e_1001    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py37h90cd8ad_103    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_100    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hicmatrix                 13                         py_0    bioconda
htslib                    1.10.2               hd3b49d5_1    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               hfafb76e_1    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_2    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_2    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libssh2                   1.9.0                hab1572f_4    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib                3.1.1                    py37_2    conda-forge
matplotlib-base           3.1.1            py37h250f245_2    conda-forge
mock                      4.0.2            py37hc8dfbb8_0    conda-forge
more-itertools            8.4.0                      py_0    conda-forge
msgpack-python            1.0.0            py37h99015e2_1    conda-forge
multiprocess              0.70.10          py37h8f50634_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
nose                      1.3.7           py37hc8dfbb8_1004    conda-forge
nspr                      4.26                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numexpr                   2.7.1            py37h0da4684_1    conda-forge
numpy                     1.19.0           py37h8960a57_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pairix                    0.3.7            py37h84994c4_0    bioconda
pandas                    1.0.5            py37h0da4684_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pathlib                   1.0.1            py37hc8dfbb8_2    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.1.1                     py_1    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
psutil                    5.7.2            py37h8f50634_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pybedtools                0.8.1            py37h8270d21_2    bioconda
pybigwig                  0.3.17           py37h960e705_2    bioconda
pyfaidx                   0.5.9              pyh4c3bd37_0    bioconda
pygenometracks            3.5                      pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h8685d9f_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysam                     0.16.0.1         py37hc334e0b_1    bioconda
pytables                  3.6.1            py37h56451d4_2    conda-forge
pytest                    5.4.3            py37hc8dfbb8_0    conda-forge
python                    3.7.6           cpython_h8356626_6    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scipy                     1.5.1            py37ha3d9a3c_0    conda-forge
setuptools                49.2.0           py37hc8dfbb8_0    conda-forge
simplejson                3.17.2           py37h8f50634_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.48.0             pyh9f0ad1d_0    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.5                h6597ccf_1    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : pgt
    active env location : /home/bag/miniconda3/envs/pgt
            shell level : 1
       user config file : /home/bag/.condarc
 populated config files : /home/bag/.condarc
          conda version : 4.8.3
    conda-build version : 3.4.2
         python version : 2.7.15.final.0
       virtual packages : __glibc=2.31
       base environment : /home/bag/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bag/miniconda3/pkgs
                          /home/bag/.conda/pkgs
       envs directories : /home/bag/miniconda3/envs
                          /home/bag/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/2.7.15 Linux/5.4.0-40-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/bag/.netrc
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by h-vetinari**
Also, turn gfortran-diff into proper patch & put patches into folder.
Remove now-unnecessary patch to revert xianyi/OpenBLAS/pull/2516.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #101

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@isuruf, not sure if there's anything to revert about the pthread handling (which IIUC was also a reaction to mitigate the segfaults), I'll leave that to you.

**Comment by isuruf** [comment]
Thanks

**Comment by h-vetinari** [comment]
The ppc64le build for python 3.7 timed out upon merging this PR:
```
THE FOLLOWING PARAMETER VALUES WILL BE USED:
   FOR N                   0     1     2     3     5     9    35
   FOR ALPHA          ( 0.0, 0.0)  ( 1.0, 0.0)  ( 0.7,-0.9)  
   FOR BETA           ( 0.0, 0.0)  ( 1.0, 0.0)  ( 1.3,-1.1)  
 ROUTINES PASS COMPUTATIONAL TESTS IF TEST RATIO IS LESS THAN  
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by isuruf** [comment]
Thanks. Restarted it.

Btw, it'd be great to have you as a maintainer here. Let me know and I can add you.

**Comment by h-vetinari** [comment]
> @isuruf: Btw, it'd be great to have you as a maintainer here. Let me know and I can add you.

Thanks for the invitation, I'd be willing to help where I can. :)

**Pull request merged**
