### PR TITLE
Fix library name

### PR DESCRIPTION
**Pull request by xoviat**
FindBLAS and FindLAPACK don't find this library name.

### CODE REVIEW

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender.

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

Maybe we need to be more "fuzzy" with that phrase.

**Comment by xoviat** [comment]
@ocefpaf Any idea why the re-rendering is not happening. `conda` should have been changed to `conda.exe'; see [here](https://github.com/conda-forge/conda-smithy/blob/8d9893da14c40fc83287bb4f22bf16683bcaa24a/conda_smithy/templates/appveyor.yml.tmpl).

**Comment by ocefpaf** [comment]
> @ocefpaf Any idea why the re-rendering is not happening. `conda` should have been changed to `conda.exe'; see [here](https://github.com/conda-forge/conda-smithy/blob/8d9893da14c40fc83287bb4f22bf16683bcaa24a/conda_smithy/templates/appveyor.yml.tmpl).

It may take a while, if not I can rerender it manually.

**Comment by xoviat** [comment]
I can as well, but I think it's a bug with the heroku app.

**Comment by jakirkham** [comment]
It's rate limited by GitHub currently.

**Comment by isuruf** [comment]
@xoviat, have you ticked `allow edits from maintainer`s?

**Comment by xoviat** [comment]
That checkbox is and has been ticked; but by default.

**Comment by isuruf** [comment]
Error is `stderr: 'fatal: unable to access 'https://<github-token>@github.com/xoviat/openblas-feedstock.git/': The requested URL returned error: 403'`, but I don't know why that is

**Comment by xoviat** [comment]
You're a member of this repository I think, so you should be able to edit this PR. Can you?

**Comment by isuruf** [comment]
Yes, I can edit this PR. Something else is wrong

**Comment by xoviat** [comment]
@isuruf Since this only affects windows, which has passed, can we go ahead and merge?

**Pull request merged**
