### PR TITLE
WIP try gfortran 7 on osx

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
This works fine on osx, so closing. We can deal with rebuild failures as we go for other platforms.

**Comment by isuruf** [comment]
I'll be happy to merge this if you add both versions to `conda_build_config.yaml` so that you can test numpy.

**Comment by beckermr** [comment]
^ scipy but yeah - numpy has no fortran dep

**Pull request closed without merging**
